# Generated by Django 2.2.1 on 2019-05-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='user_resume',
            field=models.FileField(max_length=20, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='details',
            name='user_working_hour',
            field=models.DurationField(null=True),
        ),
    ]
